[workspace]
resolver = "2"                                                     # Recommended for new projects
members = ["bittorent_cli", "bittorent_daemon", "bittorrent_core"]

[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0"
