[package]
name = "bittorrent_core"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
sha1 = "0.10.6"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
