[package]
name = "bittorent_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bincode = "2.0.1"
thiserror.workspace = true
tokio = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
